version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    assignees:
      - "doubleangels"
    reviewers:
      - "doubleangels"
