version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    labels:
      - "dependabot"
    assignees:
      - "doubleangels"
    reviewers:
      - "doubleangels"
