version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: npx wrangler pages deploy dist --project-name=html
          name: Publish app

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
