name: Test development build

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.1.0"

      - name: Install dependencies
        run: npm install

      - name: Build
        id: build
        run: npm run build
