name: Handle dependabot pull request

on:
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from Dependabot
        id: dependabot-check
        run: echo "::set-output name=is_dependabot::${{ contains(github.event.pull_request.user.login, 'dependabot') }}"

  test-build:
    runs-on: ubuntu-latest
    if: ${{ needs.check-pr.outputs.is_dependabot == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21.1.0"

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  accept-pr:
    runs-on: ubuntu-latest
    if: ${{ needs.test-build.outcome == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Approve a PR if not already approved
        run: |
          gh pr checkout "$PR_URL"
            if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
          then
            gh pr review --approve "$PR_URL"
          else
            echo "PR already approved.";
          fi
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Auto-merge dependabot PR's
        if: ${{ contains(github.event.pull_request.title, 'bump')}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
